# Generated by Django 5.2.1 on 2025-05-22 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('settings', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_form_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('brand_names_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DosageTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_class_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('generics_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('monograph_link', models.URLField(blank=True, null=True)),
                ('drug_class', models.CharField(blank=True, max_length=255, null=True)),
                ('drug_class_id', models.IntegerField(blank=True, null=True)),
                ('indication', models.CharField(blank=True, max_length=255, null=True)),
                ('indication_id', models.IntegerField(blank=True, null=True)),
                ('indication_description', models.TextField(blank=True, null=True)),
                ('therapeutic_class_description', models.TextField(blank=True, null=True)),
                ('pharmacology_description', models.TextField(blank=True, null=True)),
                ('dosage_description', models.TextField(blank=True, null=True)),
                ('administration_description', models.TextField(blank=True, null=True)),
                ('interaction_description', models.TextField(blank=True, null=True)),
                ('contraindications_description', models.TextField(blank=True, null=True)),
                ('side_effects_description', models.TextField(blank=True, null=True)),
                ('pregnancy_lactation_description', models.TextField(blank=True, null=True)),
                ('precautions_description', models.TextField(blank=True, null=True)),
                ('pediatric_usage_description', models.TextField(blank=True, null=True)),
                ('overdose_effects_description', models.TextField(blank=True, null=True)),
                ('duration_treatment_description', models.TextField(blank=True, null=True)),
                ('reconstitution_description', models.TextField(blank=True, null=True)),
                ('storage_conditions_description', models.TextField(blank=True, null=True)),
                ('descriptions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('generics_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='default-slug', unique=True)),
                ('generics_count', models.IntegerField(default=0)),
                ('brand_names_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('business_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drugs/')),
                ('is_inactive', models.BooleanField(default=False)),
                ('drug_type', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('dosage_form_id', models.IntegerField(blank=True, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('mfg_id', models.IntegerField(blank=True, null=True)),
                ('package_container', models.CharField(blank=True, max_length=100, null=True)),
                ('package_size', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('generic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.generic')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.drug')),
                ('indication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.indication')),
                ('times', models.ManyToManyField(to='myapp.dosagetime')),
            ],
        ),
    ]
